name: Automatic .Net Tests

on:
  push:
    branches: 
      - Lilian
  pull_request:
    branches: 
      - Lilian 
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'AicaDocsApi.sln'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x
          
      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG

      - name: Test
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Automatic .Net Tests
          path: '**/test-results.trx'
          reporter: dotnet-trx
          fail-on-error: true
